-- ============================================================
-- POSTS — SEO blog drafts generated by monthly-seo-post
-- ============================================================

create type post_status as enum ('draft', 'published', 'archived');

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  topic text,
  title text not null,
  slug text unique not null,
  seo_description text,
  body_md text,
  hero_image_path text,
  status post_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_posts_status on public.posts(status);
create index if not exists idx_posts_published on public.posts(published_at desc);

alter table public.posts enable row level security;

create policy "published posts readable by anyone"
  on public.posts for select using (status = 'published');

create policy "posts admin all"
  on public.posts for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists trg_posts_touch on public.posts;
create trigger trg_posts_touch before update on public.posts
  for each row execute function public.touch_updated_at();
